forbiddenStringsFrom: shared-forbidden-strings.yaml
forbiddenStrings:
  - ''
sources:
  - id: adzuna
    type: api
    provider: adzuna
    enabled: true
    query:
      country: fr
      where: ''
      what: remote
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: remote télétravail full-remote
      what_exclude_remote: partiel unknown
