forbiddenStrings:
  - intern
  - stagiaire
  - junior
  - stage
  - commercial
  - marketing
  - business
  - data analyst
  - data scientist
  - data engineer
  - data architect
  - data visualization
  - data warehouse
  - data warehouse architect
  - data warehouse engineer
  - data warehouse analyst
  - ruby
  - java
  - C#
  - clients
  - client
  - VBA
  - territorial
  - paie
  - paiement
  - iot
  - ios
  - android


sources:
  - id: adzuna
    type: api
    provider: adzuna
    enabled: true
    query:
      country: fr
      where: ''
      what: remote
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: remote télétravail full-remote
      what_exclude_remote: partiel unknown
