forbiddenStringsFrom: shared-forbidden-strings.yaml

sources:
  - id: adzuna
    type: api
    provider: adzuna
    enabled: true
    query:
      country: fr
      where: caen normandie
      what: remote
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: ''
      what_exclude_remote: ''
