forbiddenStringsFrom: shared-forbidden-strings.yaml

sources:
  - id: jobspresso
    type: rss
    provider: jobspresso
    enabled: true
    query:
      feed_url: https://jobspresso.co/?feed=job_feed
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: ''
      what_exclude_remote: partiel unknown
