forbiddenStringsFrom: shared-forbidden-strings.yaml

sources:
  - id: remotive-remote
    type: api
    provider: remotive
    enabled: true
    query:
      search: typescript symfony laravel javascript PHP developer
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: remote télétravail full-remote
      what_exclude_remote: partiel unknown
