forbiddenStringsFrom: shared-forbidden-strings.yaml

sources:
  - id: welovedev-remote
    type: xhr
    provider: welovedev
    enabled: true
    query:
      query: développeur typescript
      remote: fullTime
      what_or: developpeur développement logiciel web typescript PHP symfony laravel javascript
      what_or_remote: remote télétravail full-remote
      what_exclude_remote: partiel unknown
